### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by JayForex** [Andrukas8/AR_Trading_Panel_For_MT5#2]
Great EA!
i have some Question and Suggestions
1.Can you add the option to add and set spreads and commissions, because this is also part of the trading cost,Because of this cost making it difficult to achieve the standard profit and loss ratio when your do daytrade or scalping
2.Can i set 1:2RR or 1:3RR then half posizion breakeven

**Comment by Andrukas8** [comment]
Thanks!
1. It does consider spreads, so there is no need to add them separately. As for commissions, I never worked on accounts with commissions, that's why I'm not completely sure about the mechanics and I don't want to add something I'm not using myself
2. Yes, you need to use a double order option, but before that - change the settings accordingly
